blog_homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Page:index }
    requirements:
        _method:  GET

blog_about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Page:about }
    requirements:
        _method:  GET

blog_contact:
    pattern:  /contact
    defaults: { _controller: BlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

blog_show:
  pattern: /{id}
  defaults: { _controller: BlogBundle:Blog:show }
  requirements:
      _method: GET
      id: \d+